[Interface]
PrivateKey = QBgD3KRv2hKOWeDLRE/HsI1bOSkVw0f4ota6smLQRWQ=
Address = 192.168.129.12/32


[Peer]
PublicKey = N2Sr0mlvxDX79igI7LXOB8nkRdE0I2DSHlXT/rKDJwk=
AllowedIPs = 192.168.0.0/17
Endpoint = 80.147.103.41:51820
